package pojo;
// Generated 2019-5-15 22:56:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BlskSpaceFile generated by hbm2java
 */
public class BlskSpaceFile implements java.io.Serializable {

	private Long id;
	private BlskDocInfo blskDocInfo;
	private BlskInvSpace blskInvSpace;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;

	public BlskSpaceFile() {
	}

	public BlskSpaceFile(BlskDocInfo blskDocInfo, BlskInvSpace blskInvSpace, Long deptid, Long creator, Date createtime,
			Date updatetime, String isvalidate) {
		this.blskDocInfo = blskDocInfo;
		this.blskInvSpace = blskInvSpace;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public BlskDocInfo getBlskDocInfo() {
		return this.blskDocInfo;
	}

	public void setBlskDocInfo(BlskDocInfo blskDocInfo) {
		this.blskDocInfo = blskDocInfo;
	}

	public BlskInvSpace getBlskInvSpace() {
		return this.blskInvSpace;
	}

	public void setBlskInvSpace(BlskInvSpace blskInvSpace) {
		this.blskInvSpace = blskInvSpace;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

}
