package pojo;
// Generated 2019-5-15 22:56:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BlskMaterialInfo generated by hbm2java
 */
public class BlskMaterialInfo implements java.io.Serializable {

	private Long id;
	private String code;
	private String no;
	private String model;
	private String name;
	private String type;
	private String length;
	private String width;
	private String hight;
	private String unit;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;
	private Set blskMaterialProperties = new HashSet(0);

	public BlskMaterialInfo() {
	}

	public BlskMaterialInfo(String code, String no, String model, String name, String type, String length, String width,
			String hight, String unit, Long deptid, Long creator, Date createtime, Date updatetime, String isvalidate,
			Set blskMaterialProperties) {
		this.code = code;
		this.no = no;
		this.model = model;
		this.name = name;
		this.type = type;
		this.length = length;
		this.width = width;
		this.hight = hight;
		this.unit = unit;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
		this.blskMaterialProperties = blskMaterialProperties;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLength() {
		return this.length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	public String getHight() {
		return this.hight;
	}

	public void setHight(String hight) {
		this.hight = hight;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

	public Set getBlskMaterialProperties() {
		return this.blskMaterialProperties;
	}

	public void setBlskMaterialProperties(Set blskMaterialProperties) {
		this.blskMaterialProperties = blskMaterialProperties;
	}

}
