package pojo;
// Generated 2019-5-15 22:56:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BlskSpaceAddress generated by hbm2java
 */
public class BlskSpaceAddress implements java.io.Serializable {

	private Long id;
	private BlskInvSpace blskInvSpace;
	private Long partyid;
	private String ip;
	private String longitude;
	private String latitude;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;

	public BlskSpaceAddress() {
	}

	public BlskSpaceAddress(BlskInvSpace blskInvSpace, Long partyid, String ip, String longitude, String latitude,
			Long deptid, Long creator, Date createtime, Date updatetime, String isvalidate) {
		this.blskInvSpace = blskInvSpace;
		this.partyid = partyid;
		this.ip = ip;
		this.longitude = longitude;
		this.latitude = latitude;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public BlskInvSpace getBlskInvSpace() {
		return this.blskInvSpace;
	}

	public void setBlskInvSpace(BlskInvSpace blskInvSpace) {
		this.blskInvSpace = blskInvSpace;
	}

	public Long getPartyid() {
		return this.partyid;
	}

	public void setPartyid(Long partyid) {
		this.partyid = partyid;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

}
