package pojo;
// Generated 2019-5-15 22:56:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BlskSpaceProperty generated by hbm2java
 */
public class BlskSpaceProperty implements java.io.Serializable {

	private Long id;
	private BlskInvSpace blskInvSpace;
	private String type;
	private Long materialid;
	private String runcode;
	private String storerule;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;

	public BlskSpaceProperty() {
	}

	public BlskSpaceProperty(BlskInvSpace blskInvSpace, String type, Long materialid, String runcode, String storerule, Long deptid, Long creator, Date createtime,
			Date updatetime, String isvalidate) {
		this.blskInvSpace = blskInvSpace;
		this.type = type;
		this.materialid = materialid;
		this.runcode = runcode;
		this.storerule = storerule;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public BlskInvSpace getBlskInvSpace() {
		return this.blskInvSpace;
	}

	public void setBlskInvSpace(BlskInvSpace blskInvSpace) {
		this.blskInvSpace = blskInvSpace;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	public Long getMaterialid() {
		return materialid;
	}

	public void setMaterialid(Long materialid) {
		this.materialid = materialid;
	}

	public String getRuncode() {
		return runcode;
	}

	public void setRuncode(String runcode) {
		this.runcode = runcode;
	}

	public String getStorerule() {
		return storerule;
	}

	public void setStorerule(String storerule) {
		this.storerule = storerule;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

}
