package pojo;
// Generated 2019-5-15 22:56:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BlskSpaceEquip generated by hbm2java
 */
public class BlskSpaceEquip implements java.io.Serializable {

	private Long id;
	private BlskInvSpace blskInvSpace;
	private BlskEquipInfo blskEquipInfo;
	private Long unitid;
	private String lor;
	private String state;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;

	public BlskSpaceEquip() {
	}

	public BlskSpaceEquip(BlskInvSpace blskInvSpace, BlskEquipInfo blskEquipInfo, Long unitid, String lor, String state,
			Long creator, Date createtime, Date updatetime, String isvalidate) {
		this.blskInvSpace = blskInvSpace;
		this.blskEquipInfo = blskEquipInfo;
		this.unitid = unitid;
		this.lor = lor;
		this.state = state;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public BlskInvSpace getBlskInvSpace() {
		return this.blskInvSpace;
	}

	public void setBlskInvSpace(BlskInvSpace blskInvSpace) {
		this.blskInvSpace = blskInvSpace;
	}

	public BlskEquipInfo getBlskEquipInfo() {
		return this.blskEquipInfo;
	}

	public void setBlskEquipInfo(BlskEquipInfo blskEquipInfo) {
		this.blskEquipInfo = blskEquipInfo;
	}

	public Long getUnitid() {
		return this.unitid;
	}

	public void setUnitid(Long unitid) {
		this.unitid = unitid;
	}

	public String getLor() {
		return this.lor;
	}

	public void setLor(String lor) {
		this.lor = lor;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

}
