package pojo;
// Generated 2019-5-5 10:23:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ZlxqDictionary generated by hbm2java
 */
public class ZlxqDictionary implements java.io.Serializable {

	private Long id;
	private ZlxqDictionary zlxqDictionary;
	private String dicCode;
	private String dicName;
	private String dicType;
	private String dicNode;
	private String isLeaf;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;
	private Set zlxqDictionaries = new HashSet(0);

	public ZlxqDictionary() {
	}

	public ZlxqDictionary(ZlxqDictionary zlxqDictionary, String dicCode, String dicName, String dicType, String dicNode,
			String isLeaf, Date createtime, Date updatetime, String isvalidate, Set zlxqDictionaries) {
		this.zlxqDictionary = zlxqDictionary;
		this.dicCode = dicCode;
		this.dicName = dicName;
		this.dicType = dicType;
		this.dicNode = dicNode;
		this.isLeaf = isLeaf;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
		this.zlxqDictionaries = zlxqDictionaries;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public ZlxqDictionary getZlxqDictionary() {
		return this.zlxqDictionary;
	}

	public void setZlxqDictionary(ZlxqDictionary zlxqDictionary) {
		this.zlxqDictionary = zlxqDictionary;
	}

	public String getDicCode() {
		return this.dicCode;
	}

	public void setDicCode(String dicCode) {
		this.dicCode = dicCode;
	}

	public String getDicName() {
		return this.dicName;
	}

	public void setDicName(String dicName) {
		this.dicName = dicName;
	}

	public String getDicType() {
		return this.dicType;
	}

	public void setDicType(String dicType) {
		this.dicType = dicType;
	}

	public String getDicNode() {
		return this.dicNode;
	}

	public void setDicNode(String dicNode) {
		this.dicNode = dicNode;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

	public Set getZlxqDictionaries() {
		return this.zlxqDictionaries;
	}

	public void setZlxqDictionaries(Set zlxqDictionaries) {
		this.zlxqDictionaries = zlxqDictionaries;
	}

	/**
	 * @Title: getIsLeaf <BR>
	 * @Description: please write your description <BR>
	 * @return: String <BR>
	 */
	public String getIsLeaf() {
		return isLeaf;
	}

	/**
	 * @Title: setIsLeaf <BR>
	 * @Description: please write your description <BR>
	 * @return: String <BR>
	 */
	public void setIsLeaf(String isLeaf) {
		this.isLeaf = isLeaf;
	}

}
