package pojo;

// Generated 2019-5-2 12:31:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ZlxqLog generated by hbm2java
 */
public class ZlxqLog implements java.io.Serializable {

	private long id;
	private String loginno;
	private String loginname;
	private Date logintime;
	private String loginip;
	private String logintype;
	private String message;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;
	private Set zlxqLogOperations = new HashSet(0);

	public ZlxqLog() {
	}

	public ZlxqLog(long id) {
		this.id = id;
	}

	public ZlxqLog(long id, String loginno, String loginname, Date logintime, String loginip, String logintype,
			String message, Long deptid, Long creator, Date createtime, Date updatetime, String isvalidate,
			Set zlxqLogOperations) {
		this.id = id;
		this.loginno = loginno;
		this.loginname = loginname;
		this.logintime = logintime;
		this.loginip = loginip;
		this.logintype = logintype;
		this.message = message;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
		this.zlxqLogOperations = zlxqLogOperations;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getLoginno() {
		return this.loginno;
	}

	public void setLoginno(String loginno) {
		this.loginno = loginno;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public Date getLogintime() {
		return this.logintime;
	}

	public void setLogintime(Date logintime) {
		this.logintime = logintime;
	}

	public String getLoginip() {
		return this.loginip;
	}

	public void setLoginip(String loginip) {
		this.loginip = loginip;
	}

	public String getLogintype() {
		return this.logintype;
	}

	public void setLogintype(String logintype) {
		this.logintype = logintype;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

	public Set getZlxqLogOperations() {
		return this.zlxqLogOperations;
	}

	public void setZlxqLogOperations(Set zlxqLogOperations) {
		this.zlxqLogOperations = zlxqLogOperations;
	}

}
