package pojo;
// Generated 2019-5-15 17:43:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BlskMaterialProperty generated by hbm2java
 */
public class BlskMaterialProperty implements java.io.Serializable {

	private Long id;
	private BlskMaterialInfo blskMaterialInfo;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;

	public BlskMaterialProperty() {
	}

	public BlskMaterialProperty(BlskMaterialInfo blskMaterialInfo, Long deptid, Long creator, Date createtime,
			Date updatetime, String isvalidate) {
		this.blskMaterialInfo = blskMaterialInfo;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public BlskMaterialInfo getBlskMaterialInfo() {
		return this.blskMaterialInfo;
	}

	public void setBlskMaterialInfo(BlskMaterialInfo blskMaterialInfo) {
		this.blskMaterialInfo = blskMaterialInfo;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

}
