package pojo;
// Generated 2019-5-15 17:43:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BlskBillInfo generated by hbm2java
 */
public class BlskBillInfo implements java.io.Serializable {

	private Long id;
	private String billno;
	private String billname;
	private String billtype;
	private String billLevel;
	private Long userid;
	private String username;
	private Date reqTime;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;
	private Set blskBillDetails = new HashSet(0);
	private Set blskInvIos = new HashSet(0);

	public BlskBillInfo() {
	}

	public BlskBillInfo(String billno, String billname, String billtype, String billLevel, Long userid, String username,
			Date reqTime, Long deptid, Long creator, Date createtime, Date updatetime, String isvalidate,
			Set blskBillDetails, Set blskInvIos) {
		this.billno = billno;
		this.billname = billname;
		this.billtype = billtype;
		this.billLevel = billLevel;
		this.userid = userid;
		this.username = username;
		this.reqTime = reqTime;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
		this.blskBillDetails = blskBillDetails;
		this.blskInvIos = blskInvIos;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBillno() {
		return this.billno;
	}

	public void setBillno(String billno) {
		this.billno = billno;
	}

	public String getBillname() {
		return this.billname;
	}

	public void setBillname(String billname) {
		this.billname = billname;
	}

	public String getBilltype() {
		return this.billtype;
	}

	public void setBilltype(String billtype) {
		this.billtype = billtype;
	}

	public String getBillLevel() {
		return this.billLevel;
	}

	public void setBillLevel(String billLevel) {
		this.billLevel = billLevel;
	}

	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getReqTime() {
		return this.reqTime;
	}

	public void setReqTime(Date reqTime) {
		this.reqTime = reqTime;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

	public Set getBlskBillDetails() {
		return this.blskBillDetails;
	}

	public void setBlskBillDetails(Set blskBillDetails) {
		this.blskBillDetails = blskBillDetails;
	}

	public Set getBlskInvIos() {
		return this.blskInvIos;
	}

	public void setBlskInvIos(Set blskInvIos) {
		this.blskInvIos = blskInvIos;
	}

}
