package pojo;
// Generated 2019-5-15 17:43:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BlskOrderTemplate generated by hbm2java
 */
public class BlskOrderTemplate implements java.io.Serializable {

	private Long id;
	private String no;
	private String type;
	private String orderno;
	private Long onoLine;
	private String header;
	private Long headerLine;
	private String fileLocalPath;
	private String fileServerPath;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;
	private Set blskOrderRefs = new HashSet(0);

	public BlskOrderTemplate() {
	}

	public BlskOrderTemplate(String no, String type, String orderno, Long onoLine, String header, Long headerLine,
			String fileLocalPath, String fileServerPath, Long deptid, Long creator, Date createtime, Date updatetime,
			String isvalidate, Set blskOrderRefs) {
		this.no = no;
		this.type = type;
		this.orderno = orderno;
		this.onoLine = onoLine;
		this.header = header;
		this.headerLine = headerLine;
		this.fileLocalPath = fileLocalPath;
		this.fileServerPath = fileServerPath;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
		this.blskOrderRefs = blskOrderRefs;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getOrderno() {
		return this.orderno;
	}

	public void setOrderno(String orderno) {
		this.orderno = orderno;
	}

	public Long getOnoLine() {
		return this.onoLine;
	}

	public void setOnoLine(Long onoLine) {
		this.onoLine = onoLine;
	}

	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	public Long getHeaderLine() {
		return this.headerLine;
	}

	public void setHeaderLine(Long headerLine) {
		this.headerLine = headerLine;
	}

	public String getFileLocalPath() {
		return this.fileLocalPath;
	}

	public void setFileLocalPath(String fileLocalPath) {
		this.fileLocalPath = fileLocalPath;
	}

	public String getFileServerPath() {
		return this.fileServerPath;
	}

	public void setFileServerPath(String fileServerPath) {
		this.fileServerPath = fileServerPath;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

	public Set getBlskOrderRefs() {
		return this.blskOrderRefs;
	}

	public void setBlskOrderRefs(Set blskOrderRefs) {
		this.blskOrderRefs = blskOrderRefs;
	}

}
