package com.zlxq.rbac.pojo;
// Generated 2019-5-2 12:31:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ZlxqParty generated by hbm2java
 */
public class ZlxqParty implements java.io.Serializable {

	private Long id;
	private String partyno;
	private String partname;
	private String sex;
	private String partytype;
	private String email;
	private String tel;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;
	private Set zlxqUserRoles = new HashSet(0);
	private Set zlxqPartyRelationsForPartyid1 = new HashSet(0);
	private Set zlxqPartyRelationsForPartyid2 = new HashSet(0);

	public ZlxqParty() {
	}

	public ZlxqParty(String partyno, String partname, String sex, String partytype, String email, String tel,
			Long deptid, Long creator, Date createtime, Date updatetime, String isvalidate, Set zlxqUserRoles,
			Set zlxqPartyRelationsForPartyid1, Set zlxqPartyRelationsForPartyid2) {
		this.partyno = partyno;
		this.partname = partname;
		this.sex = sex;
		this.partytype = partytype;
		this.email = email;
		this.tel = tel;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
		this.zlxqUserRoles = zlxqUserRoles;
		this.zlxqPartyRelationsForPartyid1 = zlxqPartyRelationsForPartyid1;
		this.zlxqPartyRelationsForPartyid2 = zlxqPartyRelationsForPartyid2;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPartyno() {
		return this.partyno;
	}

	public void setPartyno(String partyno) {
		this.partyno = partyno;
	}

	public String getPartname() {
		return this.partname;
	}

	public void setPartname(String partname) {
		this.partname = partname;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPartytype() {
		return this.partytype;
	}

	public void setPartytype(String partytype) {
		this.partytype = partytype;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

	public Set getZlxqUserRoles() {
		return this.zlxqUserRoles;
	}

	public void setZlxqUserRoles(Set zlxqUserRoles) {
		this.zlxqUserRoles = zlxqUserRoles;
	}

	public Set getZlxqPartyRelationsForPartyid1() {
		return this.zlxqPartyRelationsForPartyid1;
	}

	public void setZlxqPartyRelationsForPartyid1(Set zlxqPartyRelationsForPartyid1) {
		this.zlxqPartyRelationsForPartyid1 = zlxqPartyRelationsForPartyid1;
	}

	public Set getZlxqPartyRelationsForPartyid2() {
		return this.zlxqPartyRelationsForPartyid2;
	}

	public void setZlxqPartyRelationsForPartyid2(Set zlxqPartyRelationsForPartyid2) {
		this.zlxqPartyRelationsForPartyid2 = zlxqPartyRelationsForPartyid2;
	}

}
