package com.zlxq.rbac.pojo;
// Generated 2019-5-2 12:31:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ZlxqLogOperation generated by hbm2java
 */
public class ZlxqLogOperation implements java.io.Serializable {

	private long id;
	private ZlxqLog zlxqLog;
	private String opertype;
	private Date opertime;
	private String operdes;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;

	public ZlxqLogOperation() {
	}

	public ZlxqLogOperation(long id) {
		this.id = id;
	}

	public ZlxqLogOperation(long id, ZlxqLog zlxqLog, String opertype, Date opertime, String operdes, Long deptid,
			Long creator, Date createtime, Date updatetime, String isvalidate) {
		this.id = id;
		this.zlxqLog = zlxqLog;
		this.opertype = opertype;
		this.opertime = opertime;
		this.operdes = operdes;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ZlxqLog getZlxqLog() {
		return this.zlxqLog;
	}

	public void setZlxqLog(ZlxqLog zlxqLog) {
		this.zlxqLog = zlxqLog;
	}

	public String getOpertype() {
		return this.opertype;
	}

	public void setOpertype(String opertype) {
		this.opertype = opertype;
	}

	public Date getOpertime() {
		return this.opertime;
	}

	public void setOpertime(Date opertime) {
		this.opertime = opertime;
	}

	public String getOperdes() {
		return this.operdes;
	}

	public void setOperdes(String operdes) {
		this.operdes = operdes;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

}
