package com.zlxq.rbac.pojo;
// Generated 2019-5-2 12:31:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ZlxqUserRole generated by hbm2java
 */
public class ZlxqUserRole implements java.io.Serializable {

	private long id;
	private ZlxqParty zlxqParty;
	private ZlxqRole zlxqRole;
	private String reltype;
	private Long deptid;
	private Long creator;
	private Date createtime;
	private Date updatetime;
	private String isvalidate;

	public ZlxqUserRole() {
	}

	public ZlxqUserRole(long id) {
		this.id = id;
	}

	public ZlxqUserRole(long id, ZlxqParty zlxqParty, ZlxqRole zlxqRole, String reltype, Long deptid, Long creator,
			Date createtime, Date updatetime, String isvalidate) {
		this.id = id;
		this.zlxqParty = zlxqParty;
		this.zlxqRole = zlxqRole;
		this.reltype = reltype;
		this.deptid = deptid;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.isvalidate = isvalidate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ZlxqParty getZlxqParty() {
		return this.zlxqParty;
	}

	public void setZlxqParty(ZlxqParty zlxqParty) {
		this.zlxqParty = zlxqParty;
	}

	public ZlxqRole getZlxqRole() {
		return this.zlxqRole;
	}

	public void setZlxqRole(ZlxqRole zlxqRole) {
		this.zlxqRole = zlxqRole;
	}

	public String getReltype() {
		return this.reltype;
	}

	public void setReltype(String reltype) {
		this.reltype = reltype;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getIsvalidate() {
		return this.isvalidate;
	}

	public void setIsvalidate(String isvalidate) {
		this.isvalidate = isvalidate;
	}

}
